default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432

development:
  <<: *default
  database: "nwaqui_development"
  username: "postgres"
  password: "123456789"
  host: "localhost"


production:
  <<: *default
  database: nwaqui_production
  username: "username"
  password: "password"
  host: "host"

test:
  <<: *default
  database: nwaqui_test
  username: "postgres"
  password: "123456789"
  host: "localhost"
